### Functions

Define a function called 'dictionary_creator' to take in two lists and return a dictionary with key:value pair list1:list2. If the two lists are not the same size, return the word "Error" instead. 

In [ ]:
def dictionary_creator(list1, list2):
    
    ### dictionary_creator(['a', 'b', 'c'], [1,2,3]) should return {'a': 1, 'b': 2, 'c': 3}
    ### dictionary_creator(['monkeys', 'pirates', 'captains'], [1,2]) should return "Error"
    
    # your code here


In [18]:
list1 = ['a', 'b', 'c']
list2 = [100, 110, 130]
list3 = ['Yulia', 'Serbia', 'Russia']
list4 = [90, 10, 5, 15]

In [13]:
if len(list1) == len(list2):
    print('yes')
else:
    print('no')

no


In [20]:
### Ошибка возникает из-за того, что в Python ключи словаря должны быть неизменяемыми объектами (например, строки, числа, кортежи), а вы используете список [list1] в качестве ключа. Списки являются изменяемыми объектами и не могут использоваться в качестве ключей в словарях.

# Чтобы исправить эту ошибку, можно использовать неизменяемый объект, например, кортеж:

# dict = {[list1] : [list2]}

list1 = ['a', 'b', 'c']
list2 = [100, 110, 130]

# Преобразуем список в кортеж, чтобы использовать его в качестве ключа
dict = {tuple(list1): list2}

print(dict)

{('a', 'b', 'c'): [100, 110, 130]}


In [28]:
def dictionary_creator(list1, list2):
    if len(list1) == len(list2):
        dict = {tuple(list1) : list2}
        return dict
    else:
        return('Error')

In [29]:
dictionary_creator(list1, list2)

{('a', 'b', 'c'): [100, 110, 130]}

In [30]:
dictionary_creator(list1, list4)

'Error'

In [32]:
# professor's solution

def dictionary_creator(list1, list2):
    if len(list1) == len(list2):
        return dict(zip(list1, list2))
    else:
        return "Error"

### Решение

* `zip(list1, list2)`: Эта функция создаёт итератор, который объединяет элементы из обоих списков попарно. Например, если list1 = ['a', 'b', 'c'] и list2 = [100, 110, 130], zip создаст пары [('a', 100), ('b', 110), ('c', 130)].

* `dict(zip(list1, list2))`: Создаёт словарь, где элементы list1 становятся ключами, а элементы list2 — значениями. В результате получается словарь `{ 'a': 100, 'b': 110, 'c': 130 }`.
Проверка на равенство длины списков защищает от ошибок, когда количество ключей и значений не совпадает. Если длины не совпадают, функция возвращает "Error".

In [31]:
'''
END OF SECTION
'''


'\nEND OF SECTION\n'